baseURL: "https://aaronrdodd.com/"
languageCode: "en-us"
title: "Aaron's Personal Site"
theme: "PaperMod"

paginate: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
      - HTML
      - RSS
      - JSON

params:
  env: "production"
  title: "Aaron's Personal Site"
  description: "A collection of my ramblings"
  keywords: [blog, personal, portfolio]
  author: "Aaron"
  DateFormat: "2006-01-02"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableFingerprinting: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  homeInfoParams:
    title: Hi There!
    content: You've stumbled upon the weblog of Aaron Dodd.
